name: Deploy to Production

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Generar build
        run: npm run build

      - name: Desplegar a rama prod
        run: |
          # Crear directorio temporal
          mkdir -p /tmp/dist-only
          # Copiar contenido de dist a directorio temporal
          cp -r dist/* /tmp/dist-only/
          # Inicializar git en directorio temporal
          cd /tmp/dist-only
          git init
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add .
          git commit -m "Deploy: ${GITHUB_SHA}"
          git push -f origin HEAD:prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}